python3 xivapilol.py "Velveteen Halfgloves"
python3 xivapilol.py "Brass Ingot"
python3 xivapilol.py "Iron Ingot"
python3 xivapilol.py "Oak Lumber"
python3 xivapilol.py "Potion of Intelligence"
python3 xivapilol.py "Potion of Dexterity"
python3 xivapilol.py "Potion of Strength"
python3 xivapilol.py "Iron Glaive"
python3 xivapilol.py "Koppranickel Nugget"
python3 xivapilol.py "Bas-relief Cobalt Saw"